### ISSUE TITLE
Github Actions example incorrect

### ISSUE THREAD

**Issue by cefn** [google/wireit#572]
At the time of writing the Github Actions caching example reads as below. Not sure where this configuration came from but it doesn't seem to align with Github Actions at all.

Github reported to me that there's no such key as `os` and it also chokes on `cache: true`.
I replaced `os: ubuntu-20.04` with `runs-on: ubuntu-latest`. I replaced `cache: true` with `cache: "npm"` and then the workflow ran to successful completion.

```yaml
# File: .github/workflows/tests.yml

name: Tests
on: [push, pull_request]
jobs:
  tests:
    os: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: true

      # Set up GitHub Actions caching for Wireit.
      - uses: google/wireit@setup-github-actions-caching/v1

      # Install npm dependencies.
      - run: npm ci

      # Run tests. Wireit will automatically use
      # the GitHub Actions cache whenever possible.
      - run: npm test
```
